Add changes to make enableFiltersFetchOptimization
vtex-apps/search-resolver pull request #101
Opened 2020-09-30 20:56 UTC by iaronaraujo

#### What problem is this solving?

This PR adds some changes necessary to make the store setting enableFiltersFetchOptimization work. This setting is responsible for truncating facets after the 10th one and making it possible to fetch the rest with a refetch.

#### How should this be manually tested?

[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

Go to the workspace and then check on the graphql that in the FacetsV2 query the `from` value is 0 and `to` is 10 
![image](https://user-images.githubusercontent.com/8443580/94735403-14b38900-0341-11eb-8807-9bdffb44aa0d.png)
Then, on the `Color` filter, click on `show 4 more` and notice that the query was re-fetched, updating the results with every facet available!

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-10-01 18:45 UTC, icazevedo approved these changes

2020-10-01 19:52 UTC, klzns requested changes

2020-10-01 19:52 UTC, klzns commented on node/resolvers/search/facets.ts
> +      }
```suggestion
      }
      return values.slice(args.from, args.to)
```

2020-10-01 19:54 UTC, klzns approved these changes

2020-10-01 20:01 UTC, lbebber approved these changes
1 sugestao

2020-10-01 20:01 UTC, lbebber commented on node/resolvers/search/facets.ts
> +      return values.slice(args.from, args.to)
se a pessoa só passar `to`, nao da problema talvez? se der, talvez isso deve resolver

```suggestion
      return values.slice(args.from ?? 0, args.to)
```

2020-10-02 19:39 UTC, thalytafabrine approved these changes

2020-10-05 13:55 UTC, merged