Add changes to make enableFiltersFetchOptimization
vtex-apps/search-resolver pull request #104
Opened 2020-10-01 20:44 UTC by iaronaraujo

#### What problem is this solving?

This PR adds some changes necessary to make the store setting enableFiltersFetchOptimization work. This setting is responsible for truncating facets after the 10th one and making it possible to fetch the rest with a refetch.

#### How should this be manually tested?

[Workspace](https://iaronaraujo--alssports.myvtex.com/clothing/shirts/Mens?map=c,c,specificationFilter_7721)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

Same thing as https://github.com/vtex-apps/search-resolver/pull/101 but with any other filter with more than 10 facets.

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-10-05 13:13 UTC, hiagolcm commented on node/resolvers/search/facets.ts
> +        return values.slice(args.from ?? 0, args.to)
is the `if(args.from === undefined)` necessary since you are using `0` as fallback here?

2020-10-05 14:23 UTC, kaisermann requested changes

2020-10-05 14:23 UTC, kaisermann commented on node/resolvers/search/facets.ts
> +      return facet.values.length || 0
When will `facet.values.length` be something other than `0`?

```suggestion
      return facet.values.length || 0
```

2020-10-05 14:27 UTC, kaisermann requested changes

2020-10-05 14:27 UTC, kaisermann commented on node/resolvers/search/facets.ts
> +    }
`any` 👀

2020-10-05 14:35 UTC, kaisermann approved these changes

2020-10-06 17:19 UTC, thalytafabrine approved these changes

2020-10-06 18:31 UTC, merged