Feature/split correction suggestions banners add redirect and facet breadcrumb
vtex-apps/search-resolver pull request #36
Opened 2020-06-05 13:32 UTC by hiagolcm

#### What problem is this solving?

With some tests, we concluded that if we separate the banner, correction, and suggestion from the `productSearch` we would increase the search performance. This PR split these fields into three new queries: `correction`,  `searchSuggestions`, and `banners`.

This PR adds another new query: the `redirect`. It will be used to redirect the user to another page based on the search query;

Besides that, I also added a new field to `facets`: the `breadcrumb`. `vtex.search-resolver@1.x` will have more performance if the breadcrumb is coming from `facets` instead of `productSearch`.

#### How should this be manually tested?

[Workspace](https://hiago--storecomponents.myvtex.com/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

⚠️ Please, do not merge it before
- https://github.com/vtex-apps/search-graphql/pull/84

2020-06-08 21:49 UTC, chrsmutti requested changes

2020-06-08 21:49 UTC, chrsmutti commented on node/resolvers/search/index.ts
> -      correction: result.correction,
O `vtex.sae-analytics` espera esse cara no retorno do `productSearch` 😟 
No mínimo ele espera um:

```js
corrections: { mispelled: boolean }
```

Os outros campos do correction ele não usa, e coloquei lá pq o evento `vtex:pageInfo` da search page só olha o retorno da query `productSearch`.

2020-06-10 20:21 UTC, hiagolcm commented on node/resolvers/search/index.ts
> -      correction: result.correction,
verdade! tinha esquecido disso!

vc colocaria o objeto inteiro ou só o misspelled?

2020-06-15 18:22 UTC, hiagolcm commented on node/resolvers/search/index.ts
> -      correction: result.correction,
eu coloquei o `result.correction` todo. nao faz diferença já que da api vai retornar só o mispelled

2020-06-15 18:26 UTC, chrsmutti approved these changes

2020-06-17 16:48 UTC, merged