[1.x] Adds support for in/excluded payment systems
vtex-apps/search-resolver pull request #93
Opened 2020-09-14 20:58 UTC by victorhmp

#### What problem is this solving?

Currently, we support an argument in the `Installments` type called `installmentCriteria` which controls how many (and which) installment options should be returned in queries that ask for `Installments`.

However, some users need more advanced filter options, such as ignoring options from a certain `PaymentMethodName` or only taking into account options from a certain `PaymentMethodName`.

This PR adds support for two new arguments added to the `Installments` type by https://github.com/vtex-apps/search-graphql/pull/91.

#### How should this be manually tested?

Go to [Workspace](https://victormiranda--eriksbikeshop.myvtex.com/_v/private/vtex.search-graphql@0.33.0-beta.4/graphiql/v1?operationName=productSearchV3&variables=%7B%0A%20%20%22hideUnavailableItems%22%3A%20false%2C%0A%20%20%22skusFilter%22%3A%20%22ALL%22%2C%0A%20%20%22simulationBehavior%22%3A%20%22skip%22%2C%0A%20%20%22installmentCriteria%22%3A%20%22MAX_WITHOUT_INTEREST%22%2C%0A%20%20%22productOriginVtex%22%3A%20true%2C%0A%20%20%22query%22%3A%20%22cycling%2Fbicycles%2Froad%22%2C%0A%20%20%22orderBy%22%3A%20%22OrderByScoreDESC%22%2C%0A%20%20%22from%22%3A%200%2C%0A%20%20%22to%22%3A%2047%2C%0A%20%20%22excludedPaymentSystems%22%3A%20%5B%22American%20Express%22%2C%20%22Visa%22%5D%2C%0A%20%20%22selectedFacets%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22key%22%3A%20%22c%22%2C%0A%20%20%20%20%20%20%22value%22%3A%20%22cycling%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22key%22%3A%20%22c%22%2C%0A%20%20%20%20%20%20%22value%22%3A%20%22bicycles%22%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22key%22%3A%20%22c%22%2C%0A%20%20%20%20%20%20%22value%22%3A%20%22road%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D) and perform a query such as this stripped down `products` query taken from a category page:

```graphql
query productSearchV3($query: String, $excludedPaymentSystems: [String], $fullText: String, $selectedFacets: [SelectedFacetInput], $orderBy: String, $from: Int, $to: Int, $hideUnavailableItems: Boolean = false, $skusFilter: ItemsFilter = ALL_AVAILABLE, $simulationBehavior: SimulationBehavior = default, $installmentCriteria: InstallmentsCriteria = MAX_WITHOUT_INTEREST, $productOriginVtex: Boolean = false, $fuzzy: String, $operator: Operator, $searchState: String) {
  productSearch(query: $query, fullText: $fullText, selectedFacets: $selectedFacets, orderBy: $orderBy, from: $from, to: $to, hideUnavailableItems: $hideUnavailableItems, simulationBehavior: $simulationBehavior, productOriginVtex: $productOriginVtex, fuzzy: $fuzzy, operator: $operator, searchState: $searchState) {
    products {
      cacheId
      productId
      productName
      items(filter: $skusFilter) {
        name
        nameComplete
        sellers {
          sellerName
          commertialOffer {
            Installments(criteria: $installmentCriteria, excludedPaymentSystems: $excludedPaymentSystems) {
              InterestRate
              NumberOfInstallments
              Name
              PaymentSystemName
            }
          }
        }
      }
    }
  }
}
```

Tweak the values in the `excludedPaymentSystems` variable to see different results.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

Check https://github.com/vtex-apps/search-resolver/pull/92.

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

This is the same implementation from https://github.com/vtex-apps/search-resolver/pull/92, but for the `1.x` major.

2020-09-14 21:00 UTC, victorhmp commented on node/package.json
> +    "vtex.search-graphql": "http://vtex.vtexassets.com/_v/public/typings/v1/vtex.search-graphql@0.33.0-beta.4/public"  },
Reminder to change this once https://github.com/vtex-apps/search-graphql/pull/91 is merged.

2020-09-15 12:41 UTC, thalytafabrine approved these changes

2020-09-16 15:22 UTC, klzns requested changes

2020-09-16 15:22 UTC, klzns commented on node/resolvers/search/offer.ts
> +          ({ PaymentSystemName }) =>
Same comment as https://github.com/vtex-apps/search-resolver/pull/92#discussion_r489522498

2020-09-16 16:36 UTC, klzns approved these changes

2020-09-16 17:46 UTC, merged